CREATE TABLE ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT,
  payment_id BIGINT,
  loan_id BIGINT,
  amount NUMERIC(38, 2),
  currency VARCHAR(255),
  type VARCHAR(255),
  created_at TIMESTAMP
);

CREATE TABLE processed_events (
  event_id VARCHAR(255) PRIMARY KEY,
  processed_at TIMESTAMP
);

CREATE TABLE failed_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(255),
  event_type VARCHAR(255),
  payload TEXT,
  error_message VARCHAR(255),
  created_at TIMESTAMP
);
