-- payment-service V1__init.sql
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  amount NUMERIC(38, 2),
  currency VARCHAR(255),
  status VARCHAR(255),
  reference_id VARCHAR(255),
  idempotency_key VARCHAR(255),
  created_at TIMESTAMP
);
CREATE UNIQUE INDEX uk_payments_idempotency_key ON payments (idempotency_key);
