server:
  port: 8082

spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ledgerflow_ledger
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledger-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.ledgerflow.contracts.events
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ledgerflow.contracts.events.PaymentCompletedEvent
    listener:
      ack-mode: RECORD

management:
  endpoints:
    web:
      exposure:
        include: health
