CREATE TABLE loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  amount NUMERIC(38, 2),
  currency VARCHAR(255),
  term_months INTEGER,
  status VARCHAR(255),
  created_at TIMESTAMP
);
